# Common configuration shared between all applications
configserver:
    name: Docker Payments Registry
    status: Connected to the Payments Registry running in Docker

payments:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
    
eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: http://admin:${payments.registry.password}@localhost:8761/eureka/
